### ISSUE TITLE
Add new IdResolver class

### ISSUE THREAD

**Issue by organisciak** [massivetexts/htrc-feature-reader#12]
Suggested by https://github.com/htrc/htrc-feature-reader/issues/32 and (I think) https://github.com/htrc/htrc-feature-reader/issues/23.

Currently, you can load a file on-demand from HTRC's web-based endpoint with an `id='...'` argument. Given a desire to load local files held in a folder or pairtree structure, the most elegant way seems to be extended how `id=` is interpreted. Some psuedo-code from https://github.com/htrc/htrc-feature-reader/issues/32:

```
# HTTP Option
Volume(id='htid', id_parser='http') # Default, which is just DL_URL.format(id)

# Custom Function Option
pt = lambda id: 'pairtree/root/' + utils.id2rsync(xid)
Volume(id='htid', id_parser=pt)

# Pairtree option, with global root setting
Volume.PAIRTREE_ROOT = 'pairtree/root') # Do just once
vol = Volume(id='htid', id_parser='pairtree')

# Pairtree option, with additional kwargs
vol = Volume(id='htid', id_parser='pairtree', pairtree_root='pairtree/root')
```

This isn't exactly how it should be implemented, because 1) the global argument PAIRTREE_ROOT likely doesn't fit in Volume as in the file handler/parser, and 2) I use the word 'parser' too frequently :)

Still, I like the idea of being able to set the global class variable, and it's most convenient in the above case, so I don't want to deviate too much from the above example.

**Comment by organisciak** [comment]
I don't know if this is a poor convention, but can you use a class specifically for its class attributes? i.e. would this work and not be weird?

```
from htrc_features import Config
Config.DL_URL =  ...
Config.PAIRTREE_ROOT = ....
```

That is, still allowing a custom arg on init.

**Comment by organisciak** [comment]
Also, thinking about simplicity, maybe instead of `http` the default argument for id_parser should be `infer`. That suggests a logic, so shouldn't be too confusing to users. The logic I expect: use 'http', unless `local_root` and `pairtree_root` is set, then use 'local' or 'pairtree'. This is similar to @bmschmidt's original suggestion.

**Comment by bmschmidt** [comment]
Not a complete answer, but I'd suggest `local_dir` and `pairtree_dir` instead of `local_root` and `pairtree_root`.

Assigning directly to class elements is definitely convenient, but it feels wrong to me. And there are definitely cases it would get tricky: like, if you're trying to load from two different sources (perhaps as part of a caching strategy, a network drive and a local SSD) while multithreaded (which wouldn't be crazy when slow network requests are involved.)

**Comment by bmschmidt** [comment]
See #13. My thinking is now changed; instead of local_dir and pairtree_dir, simply say "dir" and have the usage be defined by whether `storage_strategy`/`protocol`/`location` (needs a name) is 'pairtree' or 'local'.

**Comment by bmschmidt** [comment]
I'm highjacking and re-naming his issue to explain a new strategy that I think works really well.

Instead of just a `BaseParser` class, I'm now introducing two new types of classes:

1. An IdResolver class that abstracts file retrieval to the web, pairtree, etc. It's initialized with some keyword args (id, dir, compression, format) and returns, generally, a BytesIO object (or tuple of them) given an id or path and a storage scheme. (I still really prefer id-based code, but there are solid ways to think about a filepath as, itself, an ID.) It uses the format only to know what filenames to look in for the data; it handles decompression, too. This eliminates a lot of special casing. It has two methods:
    1. get(id) returns a BytesIO object (or something like that--I've still got to work out the kinks).
        For parquet, you say `ParquetResolver.get(id, suffix = 'tokens')`.
    2. put(id, object) writes a bytes IO object to the file appropriate to the system (e.g., to the right pairtree folder with gzip encoding.)

2. A FileHandler (currently baseParser) class that does parsing from a BytesIO object returned by an IdResolver. So the logic for handling url requests isn't in the JSON class, but in the HttpResolver class. This gets rid of a lot of special case code in the current JSON class, too, because it no longer has to think a lot about whether somethings online. A filehandler retrieves a file given an ID (and potentially more info, like a suffix for parquet).

A volume would typically be called like this:

```python
p = Volume(id = "coo.123465", format = "json", dir = "/bulk/hathi-ef/", id_resolver = "pairtree")
```

which resolves under the hood to

```python
p = Volume(id = "coo.123465", format = "json", id_resolver = PairtreeResolver(root = "/bulk/hathi-ef", format = "json"))
```

That lets people write their own storage schemes using `get` (which could conceivably matter b/c Portico is talking about using authentication somehow), and also means that a resolver object can have a memory, which can be useful in a few situations I'm thinking of, such as dynamically expanded pairtrees.

IdResolvers can have Reader-specific defaults. (compression is snappy for parquet, bz2 for json, etc.)

---

Above the hood, this won't really look any different, I don't think. 

The big question in my head is what to call the id_resolver argument. Some options:

* `id_resolver`
* `protocol`
* `storage_format`
* `file_location`

**Comment by bmschmidt** [comment]
One change I've made to this that clarifies things. Rather than 'put' and 'get' methods, it justuses the well established `open` method with mode of `rb` and `wb` to handle the reading and writing cases. After all, 'open' is basically a function, that returns IOBuffer.
