### ISSUE TITLE
Restore core library support for chunked parquet

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/htrc-feature-reader#19]
Isn't chunked parquet storage is a SaDDL thing that is a little finicky and boutique to include in the core library and tests. I think the 'parquet' storage format in the core library should include all the elements in the original data.

For SaDDL, I think the best route is to create a custom parser that does just what we want. I'll sketch it out in the accessing with IDs notebook, but the core logic is just to overwrite the 'write' method of the core parquet parser.

```python
class ChunkedParquetHandler(htrc_features.parsers.ParquetFileHandler):
    def __init__(self, target = 10000, chunk_strategy = 'ends', **kwargs):
        self.chunk_size = target
        self.chunk_strategy = chunk_strategy
        
        super().__init__(**kwargs)
        
    def write(self, volume, meta=True, tokens=True, section_features=False, chars=False, **kwargs):
        
        if meta:
            metastring = BytesIO(json.dumps(volume.parser.meta).encode("utf-8"))
            with self.resolver.open(self.id, **kwargs) as fout:
                fout.write(metastring)
        
        if tokens:
            feats = volume.chunked_tokenlist(target = self.chunk_size, strategy = 'ends')
            if not feats.empty:
                with self.resolver.open(id = self.id, suffix = 'tokens') as fout:
                    feats.to_parquet(fout, compression=self.compression)           
```

**Comment by bmschmidt** [comment]
An alternative to this would be--rather than having 'tokens.parquet' be either at the chunk or page level--have 'tokens.parquet' be the page level and 'chunked_tokens.parquet' be the chunked version.

**Comment by organisciak** [comment]
This test is in there to allow support of different formats for the sub-document unit. I'd also like to maintain chunks as an alternative to pages.

**Comment by bmschmidt** [comment]
Reopening and renaming from 'drop' to 'restore'  because this isn't currently support by the newer parquet write method.

I think it will need to be passed to the tokenlist call [here](https://github.com/massivetexts/htrc-feature-reader/blob/master/htrc_features/parsers.py#L499-L505).

How would you want to handle the case where you want to cache both the page-level counts, and the chunk-level counts?

**Comment by organisciak** [comment]
Oh, I didn't realize in working through your FileHandler updates that the old save_parquet method was still there! I saw you moved the code to the ParquetFileHandler and had assumed that you were re-routed save_parquet through that class, since saving tests were passing.

My design was not to save chunked tokenlists separate from page-level counts. Rather, my hope is to treat them as an iterant of lossy tokenlist saving, like saving with `pos=False`, `case=False`, or `drop_section=True` - an _alternative_ option for users that are don't need certain information and are welcome to the lossiness that at the same time ensures that I write flexible and not overly-presumptive code for working with the tokenlists.

**Comment by bmschmidt** [comment]
I hadn't quite realized it was still there either, so this is pressing. Will take a stab at resolving the problem when I get a chance. This speaks to the need for me to improve the id_resolver tests, too, because this would only pass in a very specific set of circumstances.

For SaDDL, I think we (or at least I) will need to store page level counts, not chunk level; which simply makes me wonder if *anyone* will save the chunks. But ensuring it's supported as an edge case is entirely reasonable.

How would you feel about my moving 'Volume.chunked_tokenlist' to `Volume._chunked_tokenlist` (maybe keeping a deprecation warning on the old label) and having it called through kwargs to `Volume.tokenlist`? Philosophically, that seems like the implied model you're giving; that the chunking is just a different set of options on 'tokenlist.'

**Comment by organisciak** [comment]
> How would you feel about my moving 'Volume.chunked_tokenlist' to
Volume._chunked_tokenlist

Sure! Conceptually that makes sense. Might or might not be tricky to juggle
- haven't thought too much about it.

> This speaks to the need for me to improve the id_resolver tests

The current tests were splendid for letting me know when I broke something,
but because the rewriting formats task was fairly high-level, I had trouble
triangulating where the error was. If you expand them, perhaps add some
more low-level assertions?

**Comment by bmschmidt** [comment]
Complete.
