### ISSUE TITLE
Clarify FeatureReader/Volume distinction

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/htrc-feature-reader#23]
There some duplication of code between FeatureReader and Volume. That seems not ideal

Eg.

https://github.com/massivetexts/htrc-feature-reader/blob/master/htrc_features/feature_reader.py#L237-L259

https://github.com/massivetexts/htrc-feature-reader/blob/master/htrc_features/feature_reader.py#L397-L421

And some FeatureReader methods like 'jsons' that seem more like volume-level logic.

https://github.com/massivetexts/htrc-feature-reader/blob/master/htrc_features/feature_reader.py#L280-L305

---

1. Would it make sense to stupify `FeatureReader` a little bit so that it only raises errors when it actually makes an invalid call to `Volume`?
2. Are there interesting extensions of `FeatureReader` worth making?  For instance, most of the new id_resolver classes could expose an __iter__ method. That would make it possible to initialize a FeatureReader on a directory and walk through the files in an undefined order. Or we could add something to make it easier to batch-download with rsync from a FeatureReader if files aren't present.

**Comment by organisciak** [comment]
> Would it make sense to stupify FeatureReader

I've been working to make FeatureReader dumber over the past few months while allowing it to work consistently with the past half-decade. So definitely fine with doing more of that, as long as tests pass.

> Are there interesting extensions of FeatureReader worth making?

I'm welcome to extensions if they make your workflow easier. Both of your suggestions could be cool and interesting! The 'worth making' part is up to you - I don't see a pressing need in my own research or teaching. 

Note the batch rsync download code in `utils.download_file` - when I wrote that years ago I considered putting it into the FeatureReader class but opted against it because I wasn't sure how to implement it elegantly and keep the class from bloating, especially since it needs to be presented to users as a conditioned indulgence given the partial system support for rsync. You may have some better ideas.

**Comment by bmschmidt** [comment]
Largely set here: https://github.com/massivetexts/htrc-feature-reader/pulls

FeatureReader now waits until the first volume call to fill in 'default' and "None' arguments; and does so just by copying the refs from the volume.
