### ISSUE TITLE
Caching http downloads

### ISSUE THREAD

**Issue by bmschmidt** [massivetexts/htrc-feature-reader#24]
My last new feature issue, swear to God. And I know you rightly fear over-engineering, but it's an important one for novice users; it addresses the other use case left over from #13.

## Scenario, then proposal

Someone takes a workshop in HTRC features. (I'm teaching one at NYC's DH week next Friday! I will finish all of my edits by then.) They code something that works with a list of IDs; maybe creating a workset on the web, or something. The way they create a workset will certainly involve HTIDs (not, god help us, the filesystem-safe format (`ark+==123...`). 

This is now  supported with id-first loading: **but** it's supported in a really unpleasant way, which is that every time they call `Volume` they download from the web. This is bad for them because it makes the process seem slow (they might not even realize what's going on); and it's impolite to the upstream servers. If they're editing a loop, they might end up downloading the same json file a dozen times. Currently, to fix that, they've got to jump out of their notebook into a rather complicated set of rsync calls that might not work on their system... etc.

In the `hathidy` R package (written for humanities grad students in a class) I automatically download to a `tmpdir`, and urge them through stderr to enter the location of pairtree for permanent caching by typing `options(local_hathi_dir="~/hathi-ef")` or something. I think this is a good solution in R, but it's really not pythonic.

## Proposal

The default id_resolver for an id with no dir is not 'http' if dir is None and "local" if dir is not `None`. Instead, it's `cache_local` in both cases, which works the following way.

1. If dir is None, dir is set to to `os.path.join(tempfile.gettempdir(), "hathi-ef")` (which I think should be persistent for a full session, then eliminated) with a warning to consider setting a dir.
2. If dir is not None, `dir` is used as pass.
3. Subsequent volume calls first try 'local'; if that fails, they try 'http' but cache the file to 'local' using 'bz2' compression.

`cache_pairtree` and `cache_ziptree` are also added. (`cache_path` is *possible*, but would actually require writing new code, which those two wouldn't.) Changing 'format' to 'parquet' in any of these three cases would first seek parquet from the filesystem, then download json from http if it's not found.

Another option would be to add 'cache' as yet another parameter, and let it be simply any valid IdResolver arg. But that's confusing because `Volume(...id_resolver = "default", cache = "http")` looks like you want to cache to the web, not cache *from* web.  `Volume(...id_resolver = "default", cache = True, fallback = "http")` is clear, but will make the docstring for `Volume` endless and confusing.

Under the hood, this will call a new instance of the class `CacheIdResolver`. It's a superclass of IdResolver that is `__init__`ed by two IdResolvers, and works pretty much like the example in the notebook from earlier.

## Issues

* HTTP isn't as good as Rsync.
* May make the docstring more confusing.
* On very strange systems, `tempfile.gettempdir()` (which resolves to `/tmp` on my Ubuntu and `/var/folders/84/dvp0h0kn22qcx_0z_hn_b36w0000gn/T` on my Mac.) might resolve to `"."`. 
* Maybe it's rude to users to take up their disk space. (Although they can save their space just by specifying `id_resolver="http"`, and the warning message can say that.)

**Comment by bmschmidt** [comment]
The basic implementation of caching turns out to be really short and [kind of a nifty piece of code--rather needing than a general CacheIdResolver class, I just create an entirely new subclass inside a closure for every combination of storage you might want.](https://github.com/massivetexts/htrc-feature-reader/blob/caching/htrc_features/resolvers.py#L350-L400) Keeping on a separate branch because for now it has no defaults and doesn't work for Parquet because parquet doesn't raise errors quickly enough right now.

**Comment by organisciak** [comment]
I'm not sure about this as a default use case, but maybe an option? I can see value for a cache that builds as you go along, though maybe not for introductory users. Still, if the cache is temporary, it might be fine.

I deliberately avoided caching with the HTTP interface when I first wrote it because I'm of the `yield` mentality for use - hold something when you need it, then let it cycle out. Generally, you only need a volume when it's open, and rarely need it again after it's been closed. What's the context for your workshop where you're repeated running `Volume` for the same volume? As a general rule, I'd think there's a better alternative, but I don't know your specifics.

Moving forward, I propose:
- renaming it to `cached_http` - If the goal of the id_resolver is to contextualize what is being done when you use an id argument, the current naming does not fit.
- not warning to set a dir if you haven't: this undermines your argument (and all the new code) to encourage thinking about ids rather than files, and makes basic use more confusing.
- thinking about error cases. With the new refactor, it's easy to accidentally call an HTTP call if you miss an argument or two (e.g. trying to load parquet with just an id and dir). Debugging this is confusing because it loads the file - but from the web. I added a cautionary check that warns when you have id_resolver='http' and dir set; if that check isn't possible, are there other ways can we warn people against unexpected HTTP calls when they mean to be loading from elsewhere?

**Comment by bmschmidt** [comment]
# Why: no one gets code right the first time.

My thought is not that finished code will recall Volume many times, but that development processes always do. You're right that there's a better alternative, but we want to make things less painful for beginners who right bad code. (The corollary, which I agree with you about, is that you also want to make things warning-heavy for people who write bad code.)

The yield mentality makes sense for the handling of memory vs on-disk.

For example:

When I do this sort of stuff, I find myself *constantly* rerunning the initial block of code. I usually start with something like this to debug.

```python
ids = ['a', 'b', 'c', 'd', ... 'm', 'n', 'o']
for volume in FeatureReader(ids[:10]):
     vol = volume.tokenlist()
     print(vol.title)
```



In a workshop, a student will probably get a few htids from online, write that loop; once it's working, they'll go and add p through z to the top. But get stuck downloading the first 10 volumes again and again.

Or consider this:

```{python}
htids = get_30_htids()
combined = []
for id in htids:
    tokens = Volume(id).tokenlist()
    combined.append(tokens)

full_dataset = pd.concat(combined)
```

Ready to move on to the next block.  But, oh, wait, there's no column with htid in there. Time to edit the cell...

```{r}
htids = get_30_htids()
combined = []
for id in htids:
    tokens = Volume(id).tokenlist()
    tokens['htid'] = id
    combined.append(tokens)

full_dataset = pd.concat(combined)
```

Now you've got to sit there for 3 minutes waiting again.

# Naming

My problem with `cached_http` is that it doesn't specify the storage format, so it would only support 'local'. Maybe `local_http_cache`. That reads like English, but also allows `first_format, second_format, caching = format.split("-")`  to split out a)ny combination of arguments--`local_pairtree_cache`, although in practice there aren't many reasons to use anything other than `http` as the second form. (Unless I  bother to write up `rsync` as an IdResolver that might be used with `FeatureReader`.)

(You could also have it be `http_cache_local`, but that doesn't read as clearly to me.)

Very slightly shorter would be `local_downloads` or `download_local`, but I think it's not any better.

#  Warning

>  not warning to set a dir if you haven't: this undermines your argument (and all the new code) to encourage thinking about ids rather than files, and makes basic use more confusing.

If it's not a default, there's no reason to warn, for sure. (Although I'd argue then there should be some notification when format = 'http' without being called explicitly more than 10 times, because probably someone is unaware.) But if it is a default, I don't think it's inconsistent to say that users should use ids in there code, but also be aware about where they're keeping their data generally.

**Comment by organisciak** [comment]
Great. Let's implement it. If the default is to cache to a tempfile, this
fits as the default id_resolver arg. The check for overuse sounds like a
good option to encourage better practice at scale.

local_http_cache is fine. I'll leave it to you, while logging my thoughts:
a) Sticking to local seems sensible for this use, rather than trying to
support an open-ended interface b) I liked the verb 'cached' because it
signals that the 'http' is the part that described how the id is resolved,
and caching is a modifier on how that's handled, where the noun is a bit
odder as a response to 'how is the id resolved'.

**Comment by bmschmidt** [comment]
OK. I'm implement it as `locally_cached_http`, which I think is quite for the single case here. Without the adverb, it's hard to know which direction it goes in.

Unless you have objections I'll build in support also for `pairtree_cached_http` and the rest, but leave it undocumented and put in a deprecation warning if anyone tries to use it. If I find it personally useful, I might stick it around.

**Comment by organisciak** [comment]
Sounds good!

**Comment by bmschmidt** [comment]
Implemented in https://github.com/massivetexts/htrc-feature-reader/tree/caching.

'locally_cached_http' is the default. (This broke a test because it now successfully resolved online!)

'pairtree_cached_local' and the rest also work, although there's little reason to.

**Comment by bmschmidt** [comment]
Will be resolved by https://github.com/massivetexts/htrc-feature-reader/pull/25
